### ISSUE TITLE
Doesn't compile from trunk

### ISSUE THREAD

**Issue by nexasone** [stcarrez/ada-security#1]
OS: Ubuntu 20.04
GNAT:  9.3.0

Output Starts here ----------------------------------------------------------------------

developer  ~  Downloads ada-security-master  ./config
config.guess   config.status  config.sub     configure      
 developer  ~ Downloads  ada-security-master  ./configure 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for gprbuild... gprbuild
checking for gprclean... gprclean
checking for gprinstall... gprinstall
checking whether make sets $(MAKE)... yes
checking whether ln -s works... yes
checking shared library support... no
checking default library type... static
checking distribution build... yes
checking coverage support... no
checking number of processors... 8
checking preparing for GNAT project security... done
checking for pandoc... no
checking for dynamo... no
checking Ada Utility Library... yes
configure: creating ./config.status
config.status: creating Makefile.conf
config.status: creating security.gpr
config.status: creating security_tests.gpr
config.status: creating samples.gpr
 developer  ~  Downloads ada-security-master  make
gprbuild -m -q -p -Psecurity.gpr -XBUILD=distrib -XPROCESSORS=8 -XSECURITY_LIBRARY_TYPE=static
utilada_xml.gpr:7:17: a project with no sources cannot be a library project
gprbuild: "security.gpr" processing failed
make: *** [Makefile:53: static] Error 4

Output Ends here -----------------------------------------------------------------------

Any advice?

**Comment by stcarrez** [comment]
Sorry for my very late answer...

The build is improved now.

It is necessary to install **libxmlada-sax9-dev** before building Ada Util.

You may also get the Debian packages for Ubuntu 20.04 as described in

https://blog.vacs.fr/vacs/blogs/post.html?post=2021/03/20/AWA-2.2.0
